# .github/code-review-action.yml 
# NOTE: Intended path is .github/workflows/code-review.yml, placed here due to directory creation issues.

name: AI Code Review

on:
  issue_comment:
    types: [created]

permissions: # STILL REQUIRED for the embedded configure-aws-credentials to work
  id-token: write # Allows the action to get an OIDC token
  contents: read # For checking out the code, if your action or a step needs it.
  pull-requests: write # For posting review comments
  issues: read # For reading issue/comment details

jobs:
  review:
    # Run only if the comment body starts with "/clara-review"
    # and the comment is on a pull request.
    if: startsWith(github.event.comment.body, '/clara-review') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    # env: block for AWS_ROLE_ARN and AWS_ROLE_SESSION_NAME is removed as it's handled inside the action

    steps:
      # The consuming workflow usually checks out its own code for the action to operate on.
      # If your action is self-contained or operates only on PR data via API, this might not be strictly needed by the action itself,
      # but the action *does* read a config file from the consuming repo, so checkout is needed.
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch the PR head commit to ensure the action operates on the correct state of the code
          # that the comment corresponds to, especially for reading the config file.
          ref: ${{ github.event.issue.pull_request.head.sha }}

      - name: Run AI Review Bot Action
        id: run_ai_review
        uses: ./ # Use the action defined in the root of this repository
        with:
          # Most AWS and Jira related inputs are now configured using secrets within the action itself.
          # Only pass inputs that are intended to be configurable by the consumer.
          
          # github-token is optional, defaults in action.yml
          # github-token: ${{ secrets.GITHUB_TOKEN }} # or a PAT if extended permissions are needed by the Python script

          # Optional: Override the default Bedrock model ID (default is in action.yml)
          # bedrock-model-id: 'anthropic.claude-3-haiku-20240307-v1:0'
          
          # Optional: Override the default config file path (default is in action.yml)
          # config-path: '.github/my-custom-config.yml'
          pass # Using pass as a placeholder if no inputs are overridden

      # Optional: Add a reaction to the comment to indicate processing status
      - name: Add reaction to comment
        uses: actions/github-script@v7
        # Run regardless of the review step's success/failure
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available
          script: |
            const comment_id = ${{ github.event.comment.id }};
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Get the outcome of the previous step using its ID
            const run_status = '${{ steps.run_ai_review.outcome }}'; 
            let reaction;
            if (run_status == 'success') {
              reaction = '+1'; // Thumbs up for success
            } else if (run_status == 'failure') {
              reaction = '-1'; // Thumbs down for failure
            } else {
              reaction = 'eyes'; // Eyes for other statuses (skipped, cancelled)
            }
            try {
              await github.rest.reactions.createForIssueComment({
                owner,
                repo,
                comment_id,
                content: reaction
              });
            } catch (error) {
              console.error(`Failed to add reaction: ${error}`);
              // Don't fail the workflow if reaction fails
            } 