# .github/code-review-action.yml 
# NOTE: Intended path is .github/workflows/code-review.yml, placed here due to directory creation issues.

name: AI Code Review

on:
  issue_comment:
    types: [created]

jobs:
  review:
    # Run only if the comment body starts with "/clara-review"
    # and the comment is on a pull request.
    if: startsWith(github.event.comment.body, '/clara-review') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      contents: read       # To read code contents (checkout)
      pull-requests: write # To post review comments
      issues: read         # To read issue (comment) details

    steps:
      # Removed checkout step as the composite action should handle checkout if needed,
      # or the calling workflow should handle checking out the consuming repo's code.
      # The composite action's 'runs' steps operate in the context of the runner
      # with the consuming repository checked out at GITHUB_WORKSPACE.
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.issue.pull_request.head.sha }}
      #     fetch-depth: 0

      # The action itself (defined in action.yml) will handle setup and execution.
      # We just need to call it using 'uses'.
      - name: Run AI Review Bot Action
        id: run_ai_review # Give the step an ID for checking outcome
        # Assuming the action is in the same repository or specify owner/repo@ref
        uses: ./ # Use the action defined in the root of this repository
        with:
          # Pass required AWS secrets
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Required if using temporary credentials
          aws-region: ${{ secrets.AWS_REGION }} # Set this secret in repo/org settings
          # Optional: Override Bedrock model
          # bedrock-model-id: 'anthropic.claude-3-haiku-20240307-v1:0'
          # Optional: Override default config file path
          # config-path: '.github/my-custom-config.yml'
          
          # --- Optional: JIRA Integration --- 
          # Provide these secrets if you have enabled Jira integration 
          # in your .github/ai-reviewer.yml config file (Enabled by default).
          jira-url: ${{ secrets.JIRA_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}

      # Optional: Add a reaction to the comment to indicate processing status
      - name: Add reaction to comment
        uses: actions/github-script@v7
        # Run regardless of the review step's success/failure
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment_id = ${{ github.event.comment.id }};
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Get the outcome of the previous step using its ID
            const run_status = '${{ steps.run_ai_review.outcome }}'; 
            let reaction;
            if (run_status == 'success') {
              reaction = '+1'; // Thumbs up for success
            } else if (run_status == 'failure') {
              reaction = '-1'; // Thumbs down for failure
            } else {
              reaction = 'eyes'; // Eyes for other statuses (skipped, cancelled)
            }
            try {
              await github.rest.reactions.createForIssueComment({
                owner,
                repo,
                comment_id,
                content: reaction
              });
            } catch (error) {
              console.error(`Failed to add reaction: ${error}`);
              // Don't fail the workflow if reaction fails
            } 