# .github/code-review-action.yml 
# NOTE: Intended path is .github/workflows/code-review.yml, placed here due to directory creation issues.

name: AI Code Review

on:
  issue_comment:
    types: [created]

permissions: # STILL REQUIRED for the embedded configure-aws-credentials to work
  id-token: write
  contents: read
  pull-requests: write
  issues: read

jobs:
  review:
    # Run only if the comment body starts with "/clara-review"
    # and the comment is on a pull request.
    if: startsWith(github.event.comment.body, '/clara-review') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    # env: block for AWS_ROLE_ARN and AWS_ROLE_SESSION_NAME is removed as it's handled inside the action

    steps:
      # The 'Configure AWS Credentials' step is now embedded within the 'AI Code Review Bot Action' itself.

      - name: Run AI Review Bot Action
        id: run_ai_review
        uses: ./ # Use the action defined in the root of this repository
        with:
          # AWS OIDC and Role Chaining Configuration
          oidc-role-arn: ${{ secrets.OIDC_ROLE_ARN }}
          oidc-role-aws-region: ${{ secrets.OIDC_ROLE_AWS_REGION }}
          bedrock-role-arn: ${{ secrets.BEDROCK_ROLE_ARN }}
          bedrock-aws-region: ${{ secrets.BEDROCK_AWS_REGION }}

          # Optional: Bedrock Model Configuration (can override default in action.yml)
          # bedrock-model-id: 'anthropic.claude-3-haiku-20240307-v1:0'
          
          # Optional: Path to reviewer config file (can override default in action.yml)
          # config-path: '.github/my-custom-config.yml'

          # Optional: Jira Configuration (provide if Jira is enabled and used)
          jira-url: ${{ secrets.JIRA_URL }}                  
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}    
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}      

      # Optional: Add a reaction to the comment to indicate processing status
      - name: Add reaction to comment
        uses: actions/github-script@v7
        # Run regardless of the review step's success/failure
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically available
          script: |
            const comment_id = ${{ github.event.comment.id }};
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            // Get the outcome of the previous step using its ID
            const run_status = '${{ steps.run_ai_review.outcome }}'; 
            let reaction;
            if (run_status == 'success') {
              reaction = '+1'; // Thumbs up for success
            } else if (run_status == 'failure') {
              reaction = '-1'; // Thumbs down for failure
            } else {
              reaction = 'eyes'; // Eyes for other statuses (skipped, cancelled)
            }
            try {
              await github.rest.reactions.createForIssueComment({
                owner,
                repo,
                comment_id,
                content: reaction
              });
            } catch (error) {
              console.error(`Failed to add reaction: ${error}`);
              // Don't fail the workflow if reaction fails
            } 