# action.yml
name: 'AI Code Review Bot Action'
description: 'Runs AI-based code reviews on PR hunks triggered by a comment, using AWS Bedrock.'
author: 'Your Name or Organization'

inputs:
  github-token:
    description: 'GitHub token for API calls. Defaults to the token provided by the workflow.'
    required: false
    default: ${{ github.token }}

  # AWS and Jira configurations are now sourced from this action repository's secrets.
  # No specific inputs needed from the consuming workflow for these.

  bedrock-model-id:
    description: 'AWS Bedrock model ID to use.'
    required: false
    default: 'anthropic.claude-3-sonnet-20240229-v1:0'
  config-path:
    description: 'Path to the reviewer config file in the consuming repo.'
    required: false
    default: '.github/clara-reviewer.yml'

  # The following inputs remain technically defined but are effectively superseded by internal OIDC
  # and direct secret usage. They could be used in a non-OIDC manual credential scenario.
  aws-access-key-id:
    description: 'AWS Access Key ID. (Typically not used with internal OIDC)'
    required: false
  aws-secret-access-key:
    description: 'AWS Secret Access Key. (Typically not used with internal OIDC)'
    required: false
  aws-session-token:
    description: 'AWS Session Token. (Typically not used with internal OIDC)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}         # Secret from this action repo
        role-chaining: true
        aws-region: ${{ secrets.OIDC_ROLE_AWS_REGION }}    # Secret from this action repo
      env:
        AWS_ROLE_ARN: ${{ secrets.BEDROCK_ROLE_ARN }}      # Secret from this action repo
        AWS_ROLE_SESSION_NAME: GitHubActionAICodeReview

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        echo "Installing dependencies from ${{ github.action_path }}/requirements.txt"
        python -m pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run AI Review Script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # AWS credentials are set by the 'Configure AWS Credentials' step above.
        AWS_REGION: ${{ secrets.BEDROCK_AWS_REGION }}     # Secret from this action repo
        BEDROCK_MODEL_ID: ${{ inputs.bedrock-model-id }}
        CONFIG_PATH: ${{ inputs.config-path }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_API_URL: ${{ github.api_url }}
        PR_NUMBER: ${{ github.event.issue.number }}
        JIRA_URL: ${{ secrets.JIRA_URL }}                  # Secret from this action repo
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}    # Secret from this action repo
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}      # Secret from this action repo (HIGHLY SENSITIVE)
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: python ${{ github.action_path }}/src/main.py 